version: '3.8'

services:
  database:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db  # Aquí se guardarán los datos de MongoDB

  backend:
    image: desarrollo147/horas-extra-app-epa:latest
    build: ./horas-extra-app-epa
    container_name: backend-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/epadatabase 
      - PORT=3000
      - SECRET_JWT_SEED=Esto-Es-UnA-PalbR@_SecretA12345678
      - REFRESH_JWT_SEED=mi_clave_super_segura_refresh
      - EMAIL_USER=desarrollo.tic@epa.gov.co
      - EMAIL_PASS=kdgq zmfw yfcw mfqv
      - INICIO_JORNADA=6
      - FIN_JORNADA=18
    depends_on:
      - database

  frontend:
    image: desarrollo147/horas-extra-frontend:latest
    build: ./horas-extra-frontend
    container_name: frontend-app
    ports:
      - "5500:80"
    depends_on:
      - backend
