name: Build and Test Docker App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for backend to start
        run: sleep 10

      - name: Show backend logs (preview)
        run: docker logs backend-api

      - name: Test backend health
        run: |
          echo "Probando conexión con backend..."
          curl -f http://192.168.137.24:3000/api/health || (echo "❌ Backend no respondió correctamente" && docker logs backend-api && exit 1)

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.yml down
